---
- hosts: apache
  become: yes
  tasks:
    - include_tasks: myfile.yml
    - name: i want to install mywebserver
      apt:
        name: apache2
        state: present
    
    - name: i want to copy file i to ansible node
      template:
        src: myindex.j2
        dest: /var/www/html/index.html

  handler:
    - name: RestartWebserver
      service:
        name: apache2
        state: Restarted
