---
- hosts: apache
  become: yes
  tasks:
    - name: i want to install java on ubuntu server
      apt:
        name: "{{myjavapackforubuntu}}"
        state: present
      when: ansible_os_family =="Debian"
   
   
    - name: i want to install java on RedHat server
      yum: 
       name: "{{myjavapackforredhat}}"
       state: present
      when: ansible_os_family =="RedHat"
