---
- name: i want to create tomcat group 
  group: 
    name: tomcat
    state: present

- name: i want to create tomcat user
  user:
    name: tomcat
    shell: /bin/bash
    group:  tomcat
    home: /opt/tomcat
    state: present