---
- name: copy tomcat user file into node side
  template:
    src: template/tomuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml

- name: copy tomcat context file into node side
  template: 
    src: template/tomcontext.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy tomcat host context file into the node side
  template:
      src: template/tomhostcontext.j2
      dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml